### ISSUE TITLE
bug: mongodb drops connection and the page breaks on first load :rage4: 

### ISSUE THREAD

**Issue by marcelovicentegc** [eutiveumsonho/eutiveumsonho#80]
This is happening quite frequently! Investigate what's up or how to retry connecting to the DB before rendering the layout

**Comment by marcelovicentegc** [comment]
Logs:

```
START RequestId: ------------------------------- Version: $LATEST
2023-12-10T20:09:56.445Z ------------------------------	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"MongoNetworkTimeoutError: connection timed out","reason":{"errorType":"MongoNetworkTimeoutError","errorMessage":"connection timed out","connectionGeneration":0,"stack":["MongoNetworkTimeoutError: connection timed out","    at connectionFailureError (/var/task/node_modules/mongodb/lib/cmap/connect.js:389:20)","    at TLSSocket.<anonymous> (/var/task/node_modules/mongodb/lib/cmap/connect.js:310:22)","    at Object.onceWrapper (node:events:631:28)","    at TLSSocket.emit (node:events:517:28)","    at TLSSocket.emit (node:domain:489:12)","    at Socket._onTimeout (node:net:598:8)","    at listOnTimeout (node:internal/timers:569:17)","    at process.processTimers (node:internal/timers:512:7)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: MongoNetworkTimeoutError: connection timed out","    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    at process.emit (node:events:529:35)","    at process.emit (node:domain:489:12)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
[ERROR] [1702238996447] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
RequestId: f383f356-e8e5-461f-8a6d-f0061a66bf86 Error: Runtime exited with error: exit status 128
Runtime.ExitError
END RequestId: --------------------------------------
REPORT RequestId -----------------------------------------	Duration: 21.31 ms	Billed Duration: 22 ms	Memory Size: 1024 MB	Max Memory Used: 131 MB
```

**Comment by marcelovicentegc** [comment]
For some odd reason, it seems this error happens most at Latin American countries

```json
{
	"id": "AgAAAYxVWceMQyasmgAAAAAAAAAYAAAAAEFZeFZXYzkxQUFCZjc3WDJlS1p1V1FBQQAAACQAAAAAMDE4YzU1NTktY2QyYy00OWNjLTk1ODktY2MzNzNkYjczMzY3",
	"content": {
		"timestamp": "2023-12-10T20:09:56.364Z",
		"tags": [
			"source:vercel",
			"datadog.submission_auth:private_api_key"
		],
		"host": "eutiveumsonho-kt8cmlwld-oficinadomarcelo.vercel.app",
		"service": "eutiveumsonho.com",
		"message": "START RequestId: f383f356-e8e5-461f-8a6d-f0061a66bf86 Version: $LATEST\n2023-12-10T20:09:56.445Z\tf87bdc52-7474-488e-93a3-713702d5647a\tERROR\tUnhandled Promise Rejection \t{\"errorType\":\"Runtime.UnhandledPromiseRejection\",\"errorMessage\":\"MongoNetworkTimeoutError: connection timed out\",\"reason\":{\"errorType\":\"MongoNetworkTimeoutError\",\"errorMessage\":\"connection timed out\",\"connectionGeneration\":0,\"stack\":[\"MongoNetworkTimeoutError: connection timed out\",\"    at connectionFailureError (/var/task/node_modules/mongodb/lib/cmap/connect.js:389:20)\",\"    at TLSSocket.<anonymous> (/var/task/node_modules/mongodb/lib/cmap/connect.js:310:22)\",\"    at Object.onceWrapper (node:events:631:28)\",\"    at TLSSocket.emit (node:events:517:28)\",\"    at TLSSocket.emit (node:domain:489:12)\",\"    at Socket._onTimeout (node:net:598:8)\",\"    at listOnTimeout (node:internal/timers:569:17)\",\"    at process.processTimers (node:internal/timers:512:7)\"]},\"promise\":{},\"stack\":[\"Runtime.UnhandledPromiseRejection: MongoNetworkTimeoutError: connection timed out\",\"    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)\",\"    at process.emit (node:events:529:35)\",\"    at process.emit (node:domain:489:12)\",\"    at emit (node:internal/process/promises:149:20)\",\"    at processPromiseRejections (node:internal/process/promises:283:27)\",\"    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)\"]}\n[ERROR] [1702238996447] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.\nRequestId: f383f356-e8e5-461f-8a6d-f0061a66bf86 Error: Runtime exited with error: exit status 128\nRuntime.ExitError\nEND RequestId: f383f356-e8e5-461f-8a6d-f0061a66bf86\nREPORT RequestId: f383f356-e8e5-461f-8a6d-f0061a66bf86\tDuration: 21.31 ms\tBilled Duration: 22 ms\tMemory Size: 1024 MB\tMax Memory Used: 131 MB",
		"attributes": {
			"source": "lambda",
			"branch": "main",
			"network": {
				"client": {
					"geoip": {
						"continent": {
							"code": "SA",
							"name": "South America"
						},
						"country": {
							"name": "Bolivia",
							"iso_code": "BO"
						},
						"subdivision": {
							"name": "La Paz Department",
							"iso_code": "BO-L"
						},
						"as": {
							"number": "AS6568",
							"route": "181.115.130.0/24",
							"domain": "entel.bo",
							"name": "Entel S.A. - EntelNet",
							"type": "isp"
						},
						"city": {
							"name": "La Paz"
						},
						"timezone": "America/La_Paz",
						"ipAddress": "181.115.130.206",
						"location": {
							"latitude": -16.5,
							"longitude": -68.15
						}
					}
				}
			},
			"proxy": {
				"referer": "https://eutiveumsonho.com/es?gclid=EAIaIQobChMI-8mk77DpggMV--L9BR1dqwl4EAEYASAAEgLUa_D_BwE",
				"method": "GET",
				"scheme": "https",
				"errorCode": "FUNCTION_INVOCATION_FAILED",
				"vercelId": "kc6km-1702238996364-9f37efccdce0",
				"userAgent": [
					"Mozilla/5.0 (Linux; Android 11; SM-A207M Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.193 Mobile Safari/537.36"
				],
				"vercelCache": "HIT",
				"lambdaRegion": "iad1",
				"pathType": "FUNC",
				"cacheId": "-",
				"path": "/api/auth/session",
				"clientIp": "181.115.130.206",
				"host": "eutiveumsonho.com",
				"region": "gru1",
				"timestamp": 1702238996364,
				"statusCode": 500
			},
			"path": "api/auth/[...nextauth]",
			"environment": "production",
			"lambda": {
				"duration": 21310000,
				"execution": 22528,
				"memorysize": 1024,
				"request_id": "f383f356-e8e5-461f-8a6d-f0061a66bf86",
				"billed_duration": 22,
				"max_memory_used": 131
			},
			"requestId": "gru1::kc6km-1702238996364-9f37efccdce0",
			"deploymentId": "dpl_CJRTH7TkoakGNR8PNYe4NQEEmGxu",
			"http": {
				"status_category": "Error"
			},
			"id": "1702238996368701829317995645",
			"projectName": "eutiveumsonho",
			"projectId": "prj_GBGNmSuONLvWkgzlOneTdwpI8tk4",
			"url_host": "eutiveumsonho-kt8cmlwld-oficinadomarcelo.vercel.app",
			"timestamp": 1702238996368,
			"statusCode": -1
		}
	}
}
```

**Comment by marcelovicentegc** [comment]
Oddly enough, according to https://www.speedtest.net/global-index#mobile, Bolivia and Venezuela internet speed is not as fast as other countries were this request succeeds 99.999% of times (Brazil, Peru, Chile, US...).
